version: "3.4"
services:
  nginx:
    environment:
      - UPSTREAM_HOST=docker.for.mac.localhost:8081
    ports:
      # dev nodejs (outside of docker network) should be able to connect to nginx (publish events)
      - 8001:8001
    volumes:
      - ./certs:/run/secrets:ro
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${DATA_ROOT_DIR:-/Volumes/test}/stage:/stage:delegated