version: "3.4"
services:
  nginx:
    volumes:
      - ./certs:/run/secrets:ro
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-conf/upstream.prod.conf:/etc/nginx/upstream.conf:ro