version: "3.4"
services:
  builder:
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}-${ENV_COLOR}"
    image: electronuserland/build-server
    deploy: &DEPLOY
      # on each node labeled "builder"
      # docker node update --label-add builder=true
      mode: global
      placement:
        constraints:
          - node.labels.builder == true
          - node.labels.environment == ${ENV_COLOR}
      restart_policy:
        condition: on-failure
        max_attempts: 10

    volumes:
      - type: volume
        source: stage
        target: /stage
      - type: tmpfs
        target: /builder-tmp
    environment:
      - REDIS_ENDPOINT
      - DEBUG
      - ELECTRON_BUILDER_TMP_DIR=/builder-tmp
      - ENVIRONMENT=${ENV_COLOR}
    # about logging - https://jaxenter.com/docker-logging-gotchas-137049.html Well, docker supports journald and so, we just configure papertrail for journald.
    logging: &LOGGING
      driver: ${LOGGING_DRIVER:-journald}

  nginx:
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}-${ENV_COLOR}"
    secrets:
      - source: builder.crt.v1
        target: bundle.crt
      - source: builder.key.v1
        target: node.key
    configs:
      - source: nginx.conf.v1
        target: /etc/nginx/nginx.conf
      - source: nginx-upstream.conf.v1
        target: /etc/nginx/upstream.conf
    volumes:
      - stage:/stage
    deploy:
      <<: *DEPLOY
    logging:
      <<: *LOGGING

volumes:
  stage:

secrets:
  builder.crt.v1:
    external: true
  builder.key.v1:
    external: true

configs:
  nginx.conf.v1:
    external: true
  nginx-upstream.conf.v1:
    external: true