version: "3.4"
services:
  builder:
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}-${ENV_COLOR}"
    image: electronuserland/build-server
    deploy: &DEPLOY
      # on each node labeled "builder"
      # docker node update --label-add builder=true
      mode: global
      # nginx must access only builder on the same host. vip (virtual IP) mode causes issues on some node (cannot resolve node by virtual IP) and in any case not required (since router uses redis discovery to find build server)
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.builder == true
          - node.labels.environment == ${ENV_COLOR}
      restart_policy:
        delay: 5s
    volumes:
      - type: volume
        source: stage
        target: /stage
      - type: tmpfs
        target: /builder-tmp
    environment:
      - REDIS_ENDPOINT
      - DEBUG
      - ELECTRON_BUILDER_TMP_DIR=/builder-tmp
      - ENVIRONMENT=${ENV_COLOR}
    # about logging - https://jaxenter.com/docker-logging-gotchas-137049.html Well, docker supports journald and so, we just configure papertrail for journald.
    logging: &LOGGING
      driver: json-file
      options:
        max-size: "4m"
        max-file: "2"

  nginx:
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}-${ENV_COLOR}"
    secrets:
      - source: builder.crt.v1
        target: bundle.crt
      - source: builder.key.v1
        target: node.key
    configs:
      - source: nginx.conf.v3
        target: /etc/nginx/nginx.conf
    volumes:
      - stage:/stage
    deploy:
      <<: *DEPLOY
    logging:
      <<: *LOGGING

volumes:
  stage:

secrets:
  builder.crt.v1:
    external: true
  builder.key.v1:
    external: true

configs:
  nginx.conf.v3:
    external: true