configs:
  router-nginx.conf.v1:
    external: true
secrets:
  builder.crt.v1:
    external: true
  builder.key.v1:
    external: true
  redis.v1:
    external: true
services:
  router:
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.labels.admin == true
    environment:
      DEBUG: null
      REDIS_ENDPOINT: null
    hostname: '{{.Node.ID}}-{{.Service.Name}}'
    image: electronuserland/build-server-router@sha256:cb0765ec29606b08886b5ab80d267e9e04148fd9138915c80a033aca0218c72b
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 4m
    secrets:
    - source: redis.v1
      target: /run/secrets/redis
    volumes:
    - socket:/socket:rw
  router-nginx:
    configs:
    - source: router-nginx.conf.v1
      target: /etc/nginx/nginx.conf
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.labels.admin == true
    hostname: '{{.Node.ID}}-{{.Service.Name}}'
    image: develar/nginx-pushstream@sha256:2f74affd13515882e57f2e6ca7e7a7ffc4ba343b80be67c4fcce5e20c634c2da
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 4m
    ports:
    - mode: host
      published: 443
      target: 443
    secrets:
    - source: builder.crt.v1
      target: bundle.crt
    - source: builder.key.v1
      target: node.key
    volumes:
    - socket:/socket:rw
version: '3.4'
volumes:
  socket: {}

