name: test
version: 1.1.0
summary: test
description: test
confinement: strict
grade: stable
apps:
  sep:
    command: env TMPDIR=$XDG_RUNTIME_DIR desktop-launch $SNAP/sep
    plugs:
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
parts:
  app:
    plugin: dump
    stage-packages:
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - fontconfig-config
      - gconf2
      - libasound2
      - pulseaudio
    source: /tmp/snap-project
    after:
      - desktop-glib-only
